version: "2.1"

services:

  ###############################################################
  #    Functions service
  ###############################################################

#  marketplace:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    expose:
#      - "1108"
#    volumes:
#      - ./app.properties:/app.properties

  ###############################################################
  #    StateFun runtime
  ###############################################################

  statefun:
##    image: apache/flink-statefun-playground:latest
    image: flink-statefun-playground-custom:latest
    ports:
      - "8081:8081"
      - "8090:8090"
      - "8091:8091"
    depends_on:
      - marketplace
    volumes:
      - ./module.yaml:/module.yaml
